Form/FieldType.php
<?php
namespace Brown298\ReportBuilderBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

/**
 * Class FieldType
 * @package Brown298\ReportBuilderBundle\Form
 */
class FieldType extends AbstractType
{
    /**
     * Build form
     *
     * @param FormBuilderInterface $builder
     * @param array $options
     * @return null
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('path', null, array(
                'attr'     => array('class' => 'path'),
                'required' => false,
            ))
            ->add('function', null, array(
                 'attr'     => array('class' => 'function'),
                 'required' => false,
            ))
            ->add('alias', 'text', array(
                'label'    => 'Column Title',
                'attr'     => array('class' => 'alias'),
                'required' => false,
            ))
            ->add('sortOrder', null, array(
                'attr'     => array('class' => 'sort_order'),
                'required' => false,
            ))
        ;

    }

    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
                                    'data_class' => 'Brown298\ReportBuilderBundle\Entity\Field',
                               ));
    }


    /**
     * getName
     *
     * @return string
     */
    public function getName()
    {
        return 'field';
    }
}

Resources/views/View/index.html.twig
{% extends "Brown298ReportBuilderBundle::base.html.twig" %}

{% block stylesheets %}
    {{ parent() }}

    {% stylesheets '@Brown298ReportBuilderBundle/Resources/public/less/view.css' %}
    <link href="{{ asset_url }}" rel="stylesheet" type="text/css" />
    {% endstylesheets %}
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    {% include "Brown298ReportBuilderBundle::Assets/table.html.twig" %}
{% endblock %}

{% block content %}

    <h2>{% block title %}{{ tableService.name }}{% endblock %}</h2>
    <div class="sqlInfo" style="display: none;">
        {{ sql }}
        {#{{ dump(params) }}#}
    </div>

    <div class="parameter-form">
        {% if tableService.hasParameterForm %}
            {% set parameterForm = tableService.getParameterForm.createView %}
            <div class="section">
                <h3>Parameters</h3>
                <form action="" method="post" class="reportParameters" {{ form_enctype(parameterForm) }} onsubmit="return false;" >
                    {{ form_widget(parameterForm) }}
                    <button class="parameterFilters btn">Filter</button><br />
                </form>
            </div>
        {% endif %}

        {% if canUpdate or canDelete or canUndelete %}
            <div class="actions section">
                <h3>Actions</h3>

                {% if canUpdate %}
                    <div class="btn-group">
                        <a href="{{ path('reports_build_first', { 'reportId': report.id }) }}" class="btn">
                            Edit
                        </a>
                        <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            {% for step in steps %}
                                <li>
                                    <a href="{{ path('reports_build_step', { 'reportId': report.id, 'stepKey': step.getKey }) }}">
                                        Edit {{ step.getLabel }}
                                    </a>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                {% endif %}

                {% if canDelete %}
                    <div class="btn-group">
                        <a href="{{ path('reports_delete', { 'reportId': report.id }) }}" class="btn delete">
                            Delete
                        </a>
                    </div>
                {% endif %}

                {% if canUndelete %}
                    <div class="btn-group">
                        <a href="{{ path('reports_delete', { 'reportId': report.id }) }}" class="btn">Restore</a>
                    </div>
                {% endif %}

            </div>
        {% endif %}

    </div>

    <div class="report-table with-parameter-form scroll-horizontal">
        {{ addDataTable(dataTable.getColumns(), {
        'id':            'report',
        'bLengthChange': 0,
        'iDisplayLength': 100,
        'bInfo':         1,
        'bFilter':       0,
        'bSort':         0,
        'customParams': {
            'sDom' :    'Tlfrtip',
            'oTableTools': '{
            "sSwfPath": "/bundles/brown298reportbuilder/swf/copy_csv_xls_pdf.swf",
            "aButtons": [ "print",
                {
                    "sExtends":     "collection",
                    "sButtonText":  "Export <span class=\'caret\'></span>",
                    "sButtonClass": "",
                    "aButtons":    [ "csv", "xls", "pdf" ]
                }
            ]
        }',
        "fnServerData":    'function ( sSource, aoData, fnCallback, oSettings  ) {
            var parameterValues = jQuery("form.reportParameters").serializeArray();
            for ( var i=0; i < parameterValues.length; i++) {  aoData.push(parameterValues[i]);  }

            jQuery.ajax({
                "type": "POST",
                "data": aoData,
                "dataType": "json",
                "success":  function (data) {
                    if (data.error) {
                        alert(data.error);
                    }
                    fnCallback(data);
                    jQuery(window).trigger("resize");
                },
                "error": function(jqXHR, textStatus, error) {
                    alert("An error occured loading this page, please try again");
                }
            });
        }',
        }
        }) }}
    </div>


    <script type="text/javascript">
        jQuery(function() {
            var exportButton = jQuery('.export-button');
            var div = jQuery('.parameter-form');
            var section = jQuery('<div class="section"></div>');
            section.append('<h3>Data</h3>').append(exportButton);
            div.prepend(section);
        });
        jQuery(document).ready(function() {
            jQuery('form.reportParameters .parameterFilters').on('click', function () {
                 dTables.tables.report.api().ajax.reload();
            });
        });
    </script>
{% endblock %}